name: localy
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0
  flutter_bloc: ^6.0.1
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  google_sign_in: ^4.5.1
  get_it: ^4.0.4
  injectable: ^1.0.2
  flushbar: ^1.10.4
  uuid: ^2.0.4
  auto_route: ^0.6.6
  kt_dart: ^0.7.0+1
  json_annotation: ^3.0.1
  google_fonts: ^1.1.0
  flutter_svg: ^0.18.0
  flutter_hooks: ^0.12.0
  google_map_location_picker: ^3.2.1
  location: ^3.0.2
  google_maps_flutter: ^0.5.21+15
  geocoder: ^0.2.1
  http: ^0.12.2
  camera: ^0.5.0
  image_picker: ^0.6.0+3
  image: ^2.1.14
  path_provider: ^1.6.11
  flutter_image_compress: ^0.7.0
  firebase_storage: ^3.0.0
  image_cropper: ^1.2.3
  geoflutterfire: ^2.1.0
  cached_network_image: ^2.2.0+1
  firebase_messaging: ^6.0.16
  firebase_crashlytics: ^0.1.3+3

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: 4.1.1
  bloc_test: 7.0.0
  build_runner:
  freezed: ^0.11.4
  lint: ^1.2.0
  injectable_generator: ^1.0.2
  auto_route_generator: ^0.6.6
  json_serializable: ^3.3.0
  clippy_flutter: ^1.1.1
  remove_from_coverage: any
  lcov: 6.0.0
  bdd_widget_test: ^0.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
scripts: derry.yaml
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ic_google.svg
    - assets/images/ingredients.svg
    - assets/images/tray.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
