name: localy
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.1
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  google_sign_in: ^4.5.1
  get_it: ^4.0.4
  injectable: ^1.0.4
  flushbar: ^1.10.4
  uuid: ^2.2.0
  auto_route: ^0.6.7
  kt_dart: ^0.7.0+1
  json_annotation: ^3.0.1
  google_fonts: ^1.1.0
  flutter_svg: ^0.18.0
  flutter_hooks: ^0.13.1
  google_map_location_picker: ^3.3.3
  location: ^3.0.2
  google_maps_flutter: ^0.5.30
  geocoder: ^0.2.1
  http: ^0.12.2
  camera: ^0.5.8+5
  image_picker: ^0.6.7+4
  image: ^2.1.14
  path_provider: ^1.6.11
  flutter_image_compress: ^0.7.0
  firebase_storage: ^3.1.6
  image_cropper: ^1.3.0
  email_validator: ^1.0.5
  geoflutterfire:
    git:
      url: https://github.com/brad007/GeoFlutterFire
      ref: master
  cached_network_image: ^2.2.0+1
  firebase_messaging: ^6.0.16
  firebase_crashlytics: ^0.1.4+1
  url_launcher: ^5.5.0
  flutter_mapbox_navigation: ^0.0.11
  intl: ^0.16.1
  time_range: ^0.4.0
  flutter_local_notifications: ^1.4.4+2
  rave_flutter:
    git:
      url: https://github.com/brad007/rave_flutter
      ref: master

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: 4.1.1
  bloc_test: 7.0.0
  build_runner: ^1.10.1
  freezed: ^0.11.5
  lint: ^1.2.0
  injectable_generator: ^1.0.4
  auto_route_generator: ^0.6.8
  json_serializable: ^3.4.0
  clippy_flutter: ^1.1.1
  remove_from_coverage: any
  lcov: 6.0.0
  bdd_widget_test: ^0.1.4
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launchericon.png"

scripts: derry.yaml

flutter:
  uses-material-design: true
  assets:
    - assets/images/ic_google.svg
    - assets/images/ingredients.svg
    - assets/images/tray.svg
    - assets/images/splash.svg
    - assets/images/logo.svg
    - assets/images/logo_white.svg
    - assets/images/no_restaurant_image.svg
    - assets/launchericon.png

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
